### ISSUE TITLE
Setting up a PoolBaseActiveLearner without initialization.

### ISSUE THREAD

**Issue by HannahKirk** [webis-de/small-text#10]
Hi,
I am training a transformers model in a separate script over a pre-defined training set. I want to then use this classifier to query examples from the unlabelled pool. I can load the trained model from pre-trained pytorch model files or from `PoolBasedActiveLearner.load('test-model/active_leaner.pkl')`. 

However, I then don't want to initialise this model as it has already been trained on a portion of the labelled data. Is it possible to still query over data i.e. `learner.query()` without running the initialization step `learner.initialize_data(x_indices_train, y_train, x_indices_validation=val_indices)`? 

Alternatively is it possible to still run this initialisation step but without running any training, i.e. just ignoring all indices for initialisation or setting the number of initialisation examples to zero in `x_indices_initial = random_initialization(y_train, n_samples=0)`.

Really appreciate your help on this one! 

Thanks :)

**Comment by chschroeder** [comment]
Hi,

`PoolBasedActiveLearner.save()/load()` just writes/reads the object as it is. So after loading a previously saved active learner, you can continue you with you previously initialized model as if nothing happened in between.

The other option you mentioned is also possible, for example if your training data changes. In this case you can call `learner.initialize_data(..., retrain=False)`, where `retrain=False` to omit the training step. In your case, however, it sounds as you should not need this additional step.

**Comment by HannahKirk** [comment]
Thank you! `retrain=False` was what I was looking for as I'm also changing the data that the active learner has assess to so will have to initialise a new learner object.

**Comment by HannahKirk** [comment]
Hi @chschroeder, do you have any update on this error?

Thanks! :)

**Comment by HannahKirk** [comment]
Thanks @chschroeder. I think even with the suggested changes, there are still some problems: 
When trying to run `embeddings, proba = active_learner_pool.classifier.embed(pool, return_proba=True)`, I now get the error:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

Perhaps the pool is has not been moved `.to_device()`?

Thanks :)

**Comment by chschroeder** [comment]
Yes, this error makes sense, we need to prepare the classifier as if fit would have been called.
The error is caused by model still being on the CPU.

Append the following line to the code above:
```
active_learner_pool._clf.model = active_learner_pool._clf.model.to(self.device)
```

**Comment by chschroeder** [comment]
That was a copy/paste remnant, sorry :).

Fixed it above. What I am doing here is just copying the code from the [classifier](https://github.com/webis-de/small-text/blob/bdd004c66604ba7a210e5fed371ac93c808f473a/small_text/integrations/transformers/classifiers/classification.py#L381)

**Comment by HannahKirk** [comment]
Hi @chschroeder, I have followed this instructions in the code:
```

def initialise_learner(pt_model_path, n_classes,  pool):
  tf_model = TransformerModelArguments(pt_model_path)
  n_epochs = 0
  clf_factory = TransformerBasedClassificationFactory(tf_model,
                                                    n_classes,
                                                    n_epochs,
                                                    kwargs = dict({'device': 'cuda', 'early_stopping_no_improvement': -1}))
  active_learner_pool = PoolBasedActiveLearner(clf_factory,  RandomSampling(), pool)
  # initialise classifier
  active_learner_pool._clf = clf_factory.new()
  # initialize the underlying model
  active_learner_pool._clf.initialize_transformer(active_learner_pool._clf.cache_dir)
  active_learner_pool._clf.num_classes = n_classes
  active_learner_pool._clf.model.to(active_learner_pool._clf.device)
  return active_learner_pool
```

However, when I now try and use this model for querying with:
`selected_indices = trained_learner.query(num_samples=10)` I still get an error: `LearnerNotInitializedException`.

How should I proceed? I thought the pre-trained model would now have been initialised with the learner so that the learner could be used to query the pool.

Thanks :)

**Comment by chschroeder** [comment]
You were almost there :). Sorry, I had no time to try this myself last week, and this distant trial and error takes a bit longer.
But now I tried it myself.

I used your function and changed this:
```
# initialise classifier
active_learner_pool._clf = clf_factory.new()
```

to this:
```
# initialise classifier
active_learner_pool._clf = clf_factory.new()
active_learner_pool._x_index_to_position = dict()
```

This got me so far that that I could use `active_learner.query(...)` and `active_learner.classifier.predict(...)`.


At second thought I am questining now what we even get from the `PoolBasedActiveLearner` at this point. Just using the classifier and query strategy directly would likely result in better code.

**Comment by chschroeder** [comment]
Hi, just to give an update: this issue has not been forgotten. I would call your use case here "pre-initialized" or "externally initialized". Similar problems regarding the API exist for cold start active learning for which we now have a [notebook](https://github.com/webis-de/small-text/blob/v1.3.0/examples/notebooks/04-zero-shot-cold-start.ipynb).

Both of these use cases are difficult to realize without breaking the current API. The solution that I would prefer will likely generalize the initialization mechanism, but this will have to wait until a next major version 2.0.0.

**Comment by chschroeder** [comment]
Finally closing this. This has been done for a while and will be released with v2.0.0 soon.

Sorry, for the long wait!
